#!bin/bash
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/Cirri_b_R_variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > Cirri_b_R_variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/Embr_8h_b__variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > Embr_8h_b__variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/Embr_10h_b__variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > Embr_10h_b__variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/Embr_15h_b__variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > Embr_15h_b__variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/Embr_36h_b__variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > Embr_36h_b__variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/Epidermis_b_R_variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > Epidermis_b_R_variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/FemGonads_b_R_variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > FemGonads_b_R_variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/Gills_b_R_variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > Gills_b_R_variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/Gut_b__variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > Gut_b__variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/Hepatic_b__variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > Hepatic_b__variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/MaleGonads_b_R_variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > MaleGonads_b_R_variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/Muscle_b_R_variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > Muscle_b_R_variants_filtered_coding
/data/regvolution/mzawi/rna_editing/editing_filter/selective_editing_filter_v2.x ../variants_filtered/NeuralTube_b__variants.vcf /data/regvolution/mzawi/Bla_annot-FINAL_v4_names.gtf -d 10 -i -c > NeuralTube_b__variants_filtered_coding